// Code generated by protoc-gen-go-stub. DO NOT EDIT.
package proto

import (
	"context"

	"google.golang.org/grpc"
)

// ResourceRequirements messages
type ResourceRequirements struct {
	Gpus     int32
	GpuType  string
	MemoryGb int32
	Cpus     int32
}

type SubmitJobRequest struct {
	Name      string
	UserId    string
	Type      string
	Priority  int32
	Resources *ResourceRequirements
	Config    map[string]string
}

type SubmitJobResponse struct {
	JobId string
}

type GetJobRequest struct {
	JobId string
}

type GetJobResponse struct {
	JobId    string
	Name     string
	UserId   string
	State    string
	Priority int32
	Error    string
}

type CancelJobRequest struct {
	JobId string
}

type CancelJobResponse struct {
	Success bool
}

type ClusterStatusRequest struct{}

type ClusterStatusResponse struct {
	TotalNodes     int32
	HealthyNodes   int32
	TotalGpus      int32
	UsedGpus       int32
	GpuUtilization float32
	PendingJobs    int32
	RunningJobs    int32
}

type WatchJobsRequest struct {
	UserId string
}

type JobEvent struct {
	JobId     string
	EventType string
	State     string
	Message   string
	Timestamp int64
}

// OrchestratorServer interface
type OrchestratorServer interface {
	SubmitJob(context.Context, *SubmitJobRequest) (*SubmitJobResponse, error)
	GetJob(context.Context, *GetJobRequest) (*GetJobResponse, error)
	CancelJob(context.Context, *CancelJobRequest) (*CancelJobResponse, error)
	GetClusterStatus(context.Context, *ClusterStatusRequest) (*ClusterStatusResponse, error)
	WatchJobs(*WatchJobsRequest, Orchestrator_WatchJobsServer) error
	mustEmbedUnimplementedOrchestratorServer()
}

// UnimplementedOrchestratorServer struct
type UnimplementedOrchestratorServer struct{}

func (UnimplementedOrchestratorServer) SubmitJob(context.Context, *SubmitJobRequest) (*SubmitJobResponse, error) {
	return nil, nil
}
func (UnimplementedOrchestratorServer) GetJob(context.Context, *GetJobRequest) (*GetJobResponse, error) {
	return nil, nil
}
func (UnimplementedOrchestratorServer) CancelJob(context.Context, *CancelJobRequest) (*CancelJobResponse, error) {
	return nil, nil
}
func (UnimplementedOrchestratorServer) GetClusterStatus(context.Context, *ClusterStatusRequest) (*ClusterStatusResponse, error) {
	return nil, nil
}
func (UnimplementedOrchestratorServer) WatchJobs(*WatchJobsRequest, Orchestrator_WatchJobsServer) error {
	return nil
}
func (UnimplementedOrchestratorServer) mustEmbedUnimplementedOrchestratorServer() {}

// Orchestrator_WatchJobsServer interface
type Orchestrator_WatchJobsServer interface {
	Send(*JobEvent) error
	grpc.ServerStream
}

// RegisterOrchestratorServer registers the server
func RegisterOrchestratorServer(s grpc.ServiceRegistrar, srv OrchestratorServer) {
	s.RegisterService(&_Orchestrator_serviceDesc, srv)
}

var _Orchestrator_serviceDesc = grpc.ServiceDesc{
	ServiceName: "orchestrator.Orchestrator",
	HandlerType: (*OrchestratorServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SubmitJob",
			Handler:    _Orchestrator_SubmitJob_Handler,
		},
		{
			MethodName: "GetJob",
			Handler:    _Orchestrator_GetJob_Handler,
		},
		{
			MethodName: "CancelJob",
			Handler:    _Orchestrator_CancelJob_Handler,
		},
		{
			MethodName: "GetClusterStatus",
			Handler:    _Orchestrator_GetClusterStatus_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "WatchJobs",
			Handler:       _Orchestrator_WatchJobs_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "orchestrator.proto",
}

// Stub handlers to satisfy compiler
func _Orchestrator_SubmitJob_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	return nil, nil
}
func _Orchestrator_GetJob_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	return nil, nil
}
func _Orchestrator_CancelJob_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	return nil, nil
}
func _Orchestrator_GetClusterStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	return nil, nil
}
func _Orchestrator_WatchJobs_Handler(srv interface{}, stream grpc.ServerStream) error {
	return nil
}
